# Generated by Django 5.1 on 2024-08-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expensive_user_income_user_alter_expensive_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensive',
            old_name='time',
            new_name='date',
        ),
    ]
