# Generated by Django 5.1 on 2024-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_time_expensive_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensive',
            name='title',
        ),
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
        migrations.AddField(
            model_name='expensive',
            name='title',
            field=models.ManyToManyField(to='main.title_expensive'),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.ManyToManyField(to='main.title_income'),
        ),
    ]
